export type Edition = {
  v: string;
  available?: true;
  standalone?: false;
  beta?: true;
  $?: number[];
  r?: string;
  releaseWindow?: string;
  materials?: string[];
  gameplay?: boolean;
  size?: string;
  handle?: string;
  url?: string;
  runSize?: number;
  includesAllSim?: true;
  [field: string]: unknown;
};
export type Inclusion = string | { item: string; edition?: string; materials?: string[]; parentEditions?: string[] };
export type Item = {
  name: string;
  releaseDate?: string;
  gameplay?: true;
  gameplayContent?: string;
  kind?: string;
  accessoryType?: string;
  tags: string[];
  aliases?: string[];
  notes?: string;
  size?: string;
  editions?: Edition[];
  includes?: Inclusion[];
  requires?: string[];
  announcements?: string[];
  handle?: string;
  url?: string;
  urls?: string[];
  price?: number;
  [field: string]: unknown;
};
export const categories = ["content", "included-only", "accessories", "bundles", "homebrew"] as const;
export type Category = (typeof categories)[number];
export type Catalog = Record<Category, Record<string, Item>> & { $schema?: string };
export type Variant = {
  [field: string]: unknown;
  id: number;
  title: string;
  price: number;
  compare_at_price: number | null;
  requires_shipping: boolean;
  sku: string;
};
export type Product = { id: number; title: string; handle: string; description: string; variants: Variant[]; [field: string]: unknown };
export type Evidence = { url: string; checkedAt: string; data: Product };
export type Mapping = {
  category: Category;
  itemId: string;
  edition?: string;
  create?: Partial<Item> & Pick<Item, "name">;
  gameplay?: boolean;
  materials?: string[];
  replaceUrl?: boolean;
  releaseDate?: string;
  variantEditions?: Record<string, string>;
  variantIds?: number[];
};
